; PlatformIO Project Configuration for Vaccine Cold Chain - Node
; ESP32 WROOM + DHT11 + LEDs (Alarm, Relay, Status)

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; Libraries
lib_deps = 
    adafruit/DHT sensor library@^1.4.6
    adafruit/Adafruit Unified Sensor@^1.1.14
    https://github.com/tzapu/WiFiManager.git

; Build flags
build_flags = 
    -D CORE_DEBUG_LEVEL=3

; Upload settings (adjust COM port as needed)
; upload_port = COM3
